name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: changeYum
        run: npm config set registry http://registry.npm.taobao.org/

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: npm run deploy

      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.server_ip }} 
          user: ${{ secrets.user }}
          password: ${{ secrets.pwd }}
          local_dir: "public/"
          remote_dir: "/resource/web/website"
          delete: true